# Config format schema number
format_version: 4

###################
## Model options
model_params:
  model_architecture: "vit_tiny"

  history_num_frames: 0
  future_num_frames: 12
  step_time: 0.1
  render_ego_history: True
  use_kinematic: False
  history_num_frames_train: 0
  transform: False
  dropout: 0.0

###################
## Input raster parameters
raster_params:
  # raster image size [pixels]
  raster_size:
    - 224
    - 224
  # raster's spatial resolution [meters per pixel]: the size in the real world one pixel corresponds to.
  pixel_size:
    - 0.5
    - 0.5
  # From 0 to 1 per axis, [0.5,0.5] would show the ego centered in the image.
  ego_center:
    - 0.25
    - 0.5
  # map_type: "py_semantic"
  map_type: "py_semantic"

  # the keys are relative to the dataset environment variable
  satellite_map_key: "aerial_map/aerial_map.png"
  semantic_map_key: "semantic_map/semantic_map.pb"
  dataset_meta_key: "meta.json"

  # e.g. 0.0 include every obstacle, 0.5 show those obstacles with >0.5 probability of being
  # one of the classes we care about (cars, bikes, peds, etc.), >=1.0 filter all other agents.
  filter_agents_threshold: 0.5

  # whether to completely disable traffic light faces in the semantic rasterizer
  disable_traffic_light_faces: False

  # When set to True, the rasterizer will set the raster origin at bottom left,
  # i.e. vehicles are driving on the right side of the road.
  # With this change, the vertical flipping on the raster used in the visualization code is no longer needed.
  # Set it to False for models trained before v1.1.0-25-g3c517f0 (December 2020).
  # In that case visualisation will be flipped (we've removed the flip there) but the model's input will be correct.
  set_origin_to_bottom: True

###################
## Data loader options
train_data_loader:
  key: "scenes/train.zarr"
  ratio: 1.0
  step: 5 # 5
  epochs: 15 # 15
  batch_size: 16
  shuffle: True
  num_workers: 8
  perturb_probability: 0.5
  w_decay: 0.0
  scheme: "default"
  scheduler: "one_cycle" #  "default"
  group_type: "split" # "missions", "turns"
  split: True
  filter_type: "upper"

val_data_loader:
  key: "scenes/validate.zarr"
  batch_size: 16
  shuffle: False
  num_workers: 8
  max_scene_id: 100

###################
## Train params
train_params:
  seed: 42
  checkpoint_every_n_epochs: 10
  eval_every_n_epochs: 4
  output_name: "pretrained"
  log_relative: True
  save_relative: True
  model_path: "None"
